#!/usr/bin/env python3
"""Generate src/secrets.h from apicreds.yaml (and hardcoded WiFi creds).

Works both standalone and as a PlatformIO pre-build script.
Only rewrites if content changed (avoids unnecessary rebuilds).
"""

import os
import sys


def find_paths():
    """Return (yaml_path, out_path) based on execution context.

    apicreds.yaml is gitignored, so it doesn't exist in git worktrees by
    default. Walk up from repo_root looking for it — that handles the
    common case of working in <repo>/.worktrees/<branch>/ while the real
    file lives in <repo>/.
    """
    try:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        project_dir = os.path.dirname(script_dir)
    except NameError:
        project_dir = os.getcwd()

    repo_root = os.path.dirname(os.path.dirname(project_dir))
    out_path = os.path.join(project_dir, "src", "secrets.h")

    # Walk up from repo_root looking for apicreds.yaml. Stop at HOME or
    # filesystem root to avoid wandering into someone else's checkout.
    home = os.path.expanduser("~")
    cur = repo_root
    yaml_path = os.path.join(cur, "apicreds.yaml")
    while not os.path.exists(yaml_path):
        parent = os.path.dirname(cur)
        if parent == cur or cur == home:
            break
        cur = parent
        yaml_path = os.path.join(cur, "apicreds.yaml")

    return (yaml_path, out_path)


def parse_yaml_simple(path):
    """Minimal YAML parser — handles 'key: value' lines only."""
    result = {}
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or line.startswith("---"):
                continue
            if ":" in line:
                key, _, val = line.partition(":")
                result[key.strip()] = val.strip()
    return result


def generate():
    yaml_path, out_path = find_paths()

    api_key = ""
    if os.path.exists(yaml_path):
        data = parse_yaml_simple(yaml_path)
        api_key = data.get("api_key", "")
    else:
        print(f"WARNING: {yaml_path} not found, HELLOCLUB_API_KEY will be empty", file=sys.stderr)

    content = f'''\
#pragma once

// Auto-generated by gen_secrets.py — do not edit by hand.
// WiFi credentials
#define WIFI_SSID "i3detroit-wpa"
#define WIFI_PASS "i3detroit"

// HelloClub API key
#define HELLOCLUB_API_KEY "{api_key}"
'''

    if os.path.exists(out_path):
        with open(out_path, "r") as f:
            if f.read() == content:
                print("secrets.h unchanged")
                return

    with open(out_path, "w") as f:
        f.write(content)
    print(f"Generated {out_path}")


# PlatformIO pre-build hook
try:
    Import("env")
    generate()
except Exception:
    pass

if __name__ == "__main__":
    generate()
