[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
upload_port = /dev/tty.usbmodem5AE60214651
monitor_port = /dev/tty.usbmodem5AE60214651
board_build.cmake_extra_args =
    -DSDKCONFIG_DEFAULTS=sdkconfig.defaults
board_build.partitions = partitions.csv
